<?php

return [
    //Generic
    'method_does_not_exist' => 'Method does not exist: %s',
    'route_method_not_allowed' => 'Route method not allowed',
    'route_does_not_exist' => 'Route does not exist',
    'configuration_does_not_exist' => 'Configuration does not exist',
    'db_query_error' => 'Error executing query: %s',
    'db_connection_error' => 'Error connecting to database: %s',
    'empty_fields' => "All fields are required",
    //Registration - Login
    'max_players' => 'Maximum players limit reached',
    'user_exists' => 'Username already exists',
    'email_exists' => 'Email already exists',
    'wrong_email' => 'Email address not found',
    'wrong_password' => 'Incorrect password',
    //Game menù
    'overview' => 'Overview',
    'resources' => 'Resources',
    'facilities' => 'Facilities',
    'messages' => 'Messages',
    'logout' => 'Logout',
    //Resources
    'metal' => 'Metal',
    'crystal' => 'Crystal',
    'deuterium' => 'Deuterium',
    'energy' => 'Energy',
    'dark_matter' => 'Dark Matter',
    //Units
    "metal_mine" => "Metal Mine",
    "crystal_mine" => "Crystal Mine",
    "deuterium_synthesizer" => "Deuterium Synthesizer",
    "solar_plant" => "Solar Plant",
    "fusion_reactor" => "Fusion Reactor",
    "robot_factory" => "Robot Factory",
    "nanite_factory" => "Nanite Factory",
    "shipyard" => "Shipyard",
    "metal_store" => "Metal Storage",
    "crystal_store" => "Crystal Storage",
    "deuterium_tank" => "Deuterium Tank",
    "research_lab" => "Research Lab",
    "terraformer" => "Terraformer",
    "alliance_depot" => "Alliance Depot",
    "missile_silo" => "Missile Silo",
    "espionage_tech" => "Espionage Technology",
    "computer_tech" => "Computer Technology",
    "weapon_tech" => "Weapon Technology",
    "armour_tech" => "Armour Technology",
    "shielding_tech" => "Shielding Technology",
    "energy_tech" => "Energy Technology",
    "hyperspace_tech" => "Hyperspace Technology",
    "combustion_drive_tech" => "Combustion Drive Technology",
    "impulse_drive_tech" => "Impulse Drive Technology",
    "hyperspace_drive_tech" => "Hyperspace Drive Technology",
    "laser_tech" => "Laser Technology",
    "ion_tech" => "Ion Technology",
    "plasma_tech" => "Plasma Technology",
    "intergalactic_research_tech" => "Intergalactic Research Network",
    "graviton_tech" => "Graviton Technology",
    "small_cargo_ship" => "Small Cargo Ship",
    "large_cargo_ship" => "Large Cargo Ship",
    "light_fighter" => "Light Fighter",
    "heavy_fighter" => "Heavy Fighter",
    "cruiser" => "Cruiser",
    "battleship" => "Battleship",
    "colony_ship" => "Colony Ship",
    "recycler" => "Recycler",
    "espionage_probe" => "Espionage Probe",
    "bomber" => "Bomber",
    "solar_satellite" => "Solar Satellite",
    "destroyer" => "Destroyer",
    "battlecruiser" => "Battlecruiser",
    "deathstar" => "Death Star",
    "rocket_launcher" => "Rocket Launcher",
    "light_laser" => "Light Laser",
    "heavy_laser" => "Heavy Laser",
    "gauss_cannon" => "Gauss Cannon",
    "ion_cannon" => "Ion Cannon",
    "plasma_turret" => "Plasma Turret",
    "small_shield_dome" => "Small Shield Dome",
    "large_shield_dome" => "Large Shield Dome",
    "anti_ballistic_missile" => "Anti-Ballistic Missiles",
    "interplanetary_missile" => "Interplanetary Missiles"
];