<?php

return [
    //Generic
    'method_does_not_exist' => 'Metodo non esistente: %s',
    'route_method_not_allowed' => 'Metodo non ammesso',
    'route_does_not_exist' => 'Impossibile trovare il percorso',
    'configuration_does_not_exist', 'La configurazione non esiste',
    'db_query_error' => 'Errore durante l\'esecuzione della query: %s',
    'db_connection_error' => 'Errore durante la connessione al database: %s',
    'empty_fields' => 'È necessario compilare tutti i campi',
    //Registration - Login
    'max_players' => 'Limite di giocatori raggiunto',
    'user_exists' => 'Username già in utilizzo',
    'email_exists' => 'Email già in utilizzo',
    'wrong_email' => 'Indirizzo email non trovato',
    'wrong_password' => 'Password errata',
    //Game menù
    'overview' => 'Riepilogo',
    'resources' => 'Risorse',
    'facilities' => 'Strutture',
    'shipyard' => 'Cantiere navale',
    'defense' => 'Difesa',
    'messages' => 'Messaggi',
    'logout' => 'Logout',
    //Resources
    'metal' => 'Metallo',
    'crystal' => 'Cristallo',
    'deuterium' => 'Deuterio',
    'energy' => 'Energia',
    'dark_matter' => 'Materia oscura',
    //Units
    'metal_mine' => 'Miniera di metallo',
    'crystal_mine' => 'Miniera di cristallo',
    'deuterium_synthesizer' => 'Sintetizzatore di deuterio',
    'solar_plant' => 'Centrale solare',
    'fusion_reactor' => 'Reattore a fusione',
    'robot_factory' => 'Fabbrica dei robot',
    'nanite_factory' => 'Fabbrica naniti',
    'hangar' => 'Cantiere navale',
    'metal_store' => 'Deposito di metallo',
    'crystal_store' => 'Deposito di cristallo',
    'deuterium_tank' => 'Deposito di deuterio',
    'research_lab' => 'Laboratorio di ricerca',
    'terraformer' => 'Terraformer',
    'alliance_depot' => 'Base d\'appoggio',
    'missile_silo' => 'Base missilistica',
    'espionage_tech' => 'Tecnologia di spionaggio',
    'computer_tech' => 'Tecnologia informatica',
    'weapon_tech' => 'Tecnologia delle armi',
    'armour_tech' => 'Tecnologia delle corazze',
    'shielding_tech' => 'Tecnologia degli scudi',
    'energy_tech' => 'Tecnologia energetica',
    'hyperspace_tech' => 'Tecnologia iperspaziale',
    'combustion_drive_tech' => 'Propulsione a combustione',
    'impulse_drive_tech' => 'Propulsione a impulso',
    'hyperspace_drive_tech' => 'Propulsione ad iperspazio',
    'laser_tech' => 'Tecnologia laser',
    'ion_tech' => 'Tecnologia ionica',
    'plasma_tech' => 'Tecnologia al plasma',
    'intergalactic_research_tech' => 'Rete interplanetaria di ricerca',
    'graviton_tech' => 'Tecnologia gravitonica',
    'small_cargo_ship' => 'Cargo leggera',
    'large_cargo_ship' => 'Cargo pesante',
    'light_fighter' => 'Caccia leggero',
    'heavy_fighter' => 'Caccia pesante',
    'cruiser' => 'Incrociatore',
    'battleship' => 'Nave da guerra',
    'colony_ship' => 'Colonizzatrice',
    'recycler' => 'Riciclatrice',
    'espionage_probe' => 'Sonda spia',
    'bomber' => 'Bombardiere',
    'solar_satellite' => 'Satellite solare',
    'destroyer' => 'Corazzata',
    'battlecruiser' => 'Incrociatore da battaglia',
    'deathstar' => 'Morte nera',
    'rocket_launcher' => 'Lanciamissili',
    'light_laser' => 'Laser leggero',
    'heavy_laser' => 'Laser pesante',
    'gauss_cannon' => 'Cannone gauss',
    'ion_cannon' => 'Cannone ionico',
    'plasma_turret' => 'Cannone al plasma',
    'small_shield_dome' => 'Cupola scudo piccola',
    'large_shield_dome' => 'Cupola scudo grande',
    'anti_ballistic_missile' => 'Missili antibalistici',
    'interplanetary_missile' => 'Missili interplanetari',
    //Costs
    'cost_metal' => '<b>Metallo:</b> %s',
    'cost_crystal' => '<b>Cristallo:</b> %s',
    'cost_deuterium' => '<b>Deuterio:</b> %s',
    'cost_energy' => '<b>Energia:</b> %s',
    'building_time' => '<b>Tempo di costruzione:</b> %s',
    'build' => 'Costruisci',
    'build_next_level' => 'Amplia al livello %d'
];