<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="favicon.png">
    <title><?php echo SITE_NAME; ?></title>
    <?php
        foreach ($styleList as $cssFile) {
            echo '<link rel="stylesheet" href="' . $cssFile . '"/>' . PHP_EOL;
        }
    ?>
</head>
<body>
    <main>
	    <div id="error-message" style="display: none;"></div>
        <header>
            <div class="item">
                <a href="#"><span class="material-symbols-outlined"></span>Board</a>
            </div>
            <div class="item">|</div>
            <div class="item">
                <a href="#">Statistics</a>
            </div>
            <div class="item">|</div>
            <div class="item">
                <a href="#">Support</a>
            </div>
            <div class="item">|</div>
            <div class="item">
                <a href="#">Wiki</a>
            </div>
            <div class="item">|</div>
            <div class="item">
                <a href="/logout">Logout</a>
            </div>
        </header>
        <div class="layout">
            <div class="resources-wrapper">
                <div class="resource-odd">
                    <div class="grid">
                        <div class="cell">
                            <div class="resource-content">
                                <div class="detail1-left"><img src='../../public/images/resources/metal.webp'/></div>
                                <div class="detail2-left"><?php echo $translator->translate('metal'); ?></div>
                                <div class="detail3-left"><?php echo _prettyNumber($planet->getPlanetMetal()) ?></div>
                            </div>
                        </div>
                        <div class="cell">
                            <div class="resource-content">
                                <div class="detail1-left"><img src='../../public/images/resources/crystal.webp'/></div>
                                <div class="detail2-left"><?php echo $translator->translate('crystal'); ?></div>
                                <div class="detail3-left"><?php echo _prettyNumber($planet->getPlanetCrystal()) ?></div>
                            </div>
                        </div>
                        <div class="cell">
                            <div class="resource-content">
                                <div class="detail1-left"><img src='../../public/images/resources/deuterium.webp'/></div>
                                <div class="detail2-left"><?php echo $translator->translate('deuterium'); ?></div>
                                <div class="detail3-left"><?php echo _prettyNumber($planet->getPlanetDeuterium()) ?></div>
                            </div>
                        </div>
                        <div class="cell">
                            <div class="resource-content">
                                <div class="detail1-left"><img src='../../public/images/resources/energy.webp'/></div>
                                <div class="detail2-left"><?php echo $translator->translate('energy'); ?></div>
                                <div class="detail3-left"><?php echo(_prettyNumber($planet->getPlanetEnergyMax() - $planet->getPlanetEnergyUsed())); ?></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="resource-even">
                    center
                </div>  
                <div class="resource-odd">
                    <div class="grid">
                        <div class="cell">Cella 1</div>
                        <div class="cell">Cella 2</div>
                        <div class="cell">Cella 3</div>
                        <div class="cell">Cella 4</div>
                    </div>
                </div>  
            </div>
            <div class="main-wrapper">
            <section class="layout-content">  
                <div class="leftmenu">
                    <?php include APP_ROOT . PATH_LEFT_MENU; ?>
                </div>
                <div class="grow1">
                    <?php echo $content; ?>
                </div>
                <div class="planets">3</div>
            </section>
            </div>
        </div>
    </main>
    <script src="https://kit.fontawesome.com/c8fb982aca.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" 
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" 
        crossorigin="anonymous"></script>
    <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script> -->
    <?php
        foreach ($jsList as $jsFile) {
            echo '<script src="' . $jsFile . '"></script>' . PHP_EOL;
        }
    ?>
</body>
</html>