<ul>
    <li></li>
    <li><a href="/overview"><?php echo $translator->translate('overview'); ?></a></li>
    <li><a href="/buildings"><?php echo $translator->translate('resources'); ?></a></li>
    <li><a href="/facilities"><?php echo $translator->translate('facilities'); ?></a></li>
    <li><a href="/research"><?php echo $translator->translate('research_lab'); ?></a></li>
    <li>Albero tecnologico</li>
    <li></li>
    <li><a href="/shipyard"><?php echo $translator->translate('shipyard'); ?></a></a></li>
    <li><a href="/defense"><?php echo $translator->translate('defense'); ?></a></a></li>
    <li>Flotte</li>
    <li>Galassia</li>
    <li></li>
    <li>Alleanza</li>
    <li>Impero</li>
    <li><a href="/messages"><?php echo $translator->translate('messages'); ?></a></a></li>
    <li>Amici</li>
    <li></li>
    <li>Mercante</li>
    <li>Simulatori</li>
    <li>Opzioni</li>
    <li><a href="/logout"><?php echo $translator->translate('logout'); ?></a></a></li>
</ul>