<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
    <title><?php echo $title; ?></title>
    <link rel="stylesheet" type="text/css" href="/public/css/default.css?v=<?php echo time(); ?>">
    <script src="/public/js/base.js?v=<?php echo time(); ?>"></script>
    <script src="https://kit.fontawesome.com/c8fb982aca.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" 
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" 
        crossorigin="anonymous"></script>
    <?php if (file_exists("public/css/{$controllerName}/{$methodName}.css")): ?>
        <link rel="stylesheet" type="text/css" href="/public/css/<?php echo $controllerName; ?>/<?php echo $methodName; ?>.css?v=<?php echo time(); ?>">
    <?php endif; ?>
    <?php if (file_exists(APP_ROOT . "/public/js/{$controllerName}/{$methodName}.js")): ?>
        <script src="<?php echo BASE_URL; ?>/public/js/<?php echo $controllerName; ?>/<?php echo $methodName; ?>.js?v=<?php echo time(); ?>"></script>
    <?php endif; ?>
</head>
<body>
<body>
    <main>
	    <div id="error-message" style="display: none;"></div>
        <header>
            <div class="item">
                <a href="#"><span class="material-symbols-outlined"></span>Board</a>
            </div>
            <div class="item">|</div>
            <div class="item">
                <a href="#">Statistics</a>
            </div>
            <div class="item">|</div>
            <div class="item">
                <a href="#">Support</a>
            </div>
            <div class="item">|</div>
            <div class="item">
                <a href="#">Wiki</a>
            </div>
            <div class="item">|</div>
            <div class="item">
                <a href="/logout">Logout</a>
            </div>
        </header>
        <div class="layout">
            <div class="resources-wrapper">
                <div class="resource-odd">
                    <div class="grid">
                        <div class="cell">
                            <div class="resource-content">
                                <div class="detail1-left"><img src='../../public/resources/metal.png'/></div>
                                <div class="detail2-left"><?php echo $translator->translate('metal'); ?></div>
                                <div class="detail3-left metal"><?php echo _prettyNumber($planet->getPlanetMetal()) ?></div>
                            </div>
                        </div>
                        <div class="cell">
                            <div class="resource-content">
                                <div class="detail1-left"><img src='../../public/resources/crystal.png'/></div>
                                <div class="detail2-left"><?php echo $translator->translate('crystal'); ?></div>
                                <div class="detail3-left crystal"><?php echo _prettyNumber($planet->getPlanetCrystal()) ?></div>
                            </div>
                        </div>
                        <div class="cell">
                            <div class="resource-content">
                                <div class="detail1-left"><img src='../../public/resources/deuterium.png'/></div>
                                <div class="detail2-left"><?php echo $translator->translate('deuterium'); ?></div>
                                <div class="detail3-left deuterium"><?php echo _prettyNumber($planet->getPlanetDeuterium()) ?></div>
                            </div>
                        </div>
                        <div class="cell">
                            <div class="resource-content">
                                <div class="detail1-left"><img src='../../public/resources/energy.png'/></div>
                                <div class="detail2-left"><?php echo $translator->translate('energy'); ?></div>
                                <div class="detail3-left energy"><?php echo(_prettyNumber($planet->getPlanetEnergyMax() - $planet->getPlanetEnergyUsed())); ?></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="resource-even">
                    center
                </div>  
                <div class="resource-odd">
                    <div class="grid">
                        <div class="cell">Cella 1</div>
                        <div class="cell">Cella 2</div>
                        <div class="cell">Cella 3</div>
                        <div class="cell">Cella 4</div>
                    </div>
                </div>  
            </div>
            <div class="main-wrapper">
            <section class="layout-content"> 
                <div class="leftmenu">
                    <?php include('left_menu.phtml'); ?>
                </div>
                <div class="grow1">
                <?php //include('events.phtml'); ?>
                    <?php echo $content; ?>
                </div>
                <div class="planets">3</div>
            </section>
            </div>
        </div>
    </main>
</body>
</html>